export const API_ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  DUPLICATE_HANDLE: 'DUPLICATE_HANDLE',
  MANAGED_ACCOUNT_NOT_FOUND: 'MANAGED_ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_ARCHIVED: 'ACCOUNT_ALREADY_ARCHIVED',
  ACCOUNT_ARCHIVE_BLOCKED_BY_ACTIVE_RUN: 'ACCOUNT_ARCHIVE_BLOCKED_BY_ACTIVE_RUN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
